global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'account-service'
    metrics_path: '/api/account/metrics'
    static_configs:
      - targets: ['host.docker.internal:9000']
        labels:
          service: 'account'